botToken=${BOT_TOKEN}
botName=easy_gas_bot

spring.rabbitmq.host=easygas-rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=easyGas_user
spring.rabbitmq.password=HlRagAABYW1WQLh

user.is.admin=${USER_ADMIN}