botToken=5921142058:AAF5jdUxgMPQW4RsvLiDIZbvF5dD6o5S4vY
botName=true_boss_bot

server.port=0
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=vlad
spring.rabbitmq.password=password

user.is.admin=393223422
