botToken=5921142058:AAF5Zv76dP_aqM6_J1z4edPPyty4FMuyUvA
botName=true_boss_bot

server.port=8081
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=vlad
spring.rabbitmq.password=password