botToken=5930981685:AAEWaSlKLl7Z_vZrNQ8avNcPekWFCWEA3qw
botName=easy_gas_bot

spring.rabbitmq.host=easygas-rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=easyGas_user
spring.rabbitmq.password=HlRagAABYW1WQLh