server.port=8082

spring.rabbitmq.host=easygas-rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=easyGas_user
spring.rabbitmq.password=HlRagAABYW1WQLh

spring.application.admin.enabled=true
spring.datasource.url=jdbc:postgresql://dpg-cmanfn6d3nmc73csuc7g-a.frankfurt-postgres.render.com/easygas_postgres
spring.datasource.username=easygas_postgres_user
spring.datasource.password=0wkOv8Zq2bzg5UrfO7TgHsR6pByKYaTU
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect