plugins {
    id 'java'
    id 'java-library'
    id("org.springframework.boot") version "3.1.2"

}

group 'org.easybot'
version '1.0-SNAPSHOT'
apply from: 'versions.gradle'



subprojects {

    repositories {
        mavenCentral()
    }
        apply plugin: 'java'
        apply plugin: 'java-library'
        apply plugin: "org.springframework.boot"


    dependencies {
        api "org.telegram:telegrambots-spring-boot-starter:${telegrambotVersion}"
        api "org.springframework.boot:spring-boot-starter-parent:${springVersion}"

        testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
        testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
        implementation 'org.apache.logging.log4j:log4j-api:2.20.0'
        implementation 'org.apache.logging.log4j:log4j-core:2.20.0'
        compileOnly 'org.projectlombok:lombok:1.18.30'
        annotationProcessor 'org.projectlombok:lombok:1.18.30'

    }
}
test {
    useJUnitPlatform()
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "com.bosscorp.TelegramBotApplication"
    }
}