NEXUS_DOCKER_USERNAME=
NEXUS_DOCKER_PASSWORD=
NEXUS_USERNAME=
NEXUS_PASSWORD=
org.gradle.caching=true

org.gradle.jvmargs=

systemProp.gradle.wrapperPassword=

systemProp.gradle.wrapperUser=


systemProp.http.proxyHost=

systemProp.http.proxyPassword=

systemProp.http.proxyPort=

systemProp.http.proxyUser=

systemProp.https.nonProxyHosts=nexus.citadele.lv|localhost|*.local|genesys.parexgroup.net|172.25.17.213|172.25.17.219

systemProp.https.proxyHost=

systemProp.https.proxyPassword=

systemProp.https.proxyPort=

systemProp.https.proxyUser=

T24_URL=

WSMR_URL=
