server.port=8083

spring.liquibase.enabled=true
spring.datasource.url=jdbc:postgresql://dpg-cmanfn6d3nmc73csuc7g-a.frankfurt-postgres.render.com/easygas_postgres
spring.datasource.username=
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.change-log=classpath:db.changelog/changelog-master.yaml
spring.jpa.show-sql=true
